[package]
name = "functors"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
fontdue = "0.9.3"
font8x8 = "0.3.1"
pollster = "1.0.1"
rfd = "0.15.4"
ropey = "1.6.1"
skia-safe = { version = "0.78.2", default-features = false, features = ["binary-cache", "embed-icudtl", "textlayout"] }
wgpu = "30.0.1"
winit = "0.30.13"
